"""Stable, Shopify-valid IDs for JSON-template section and block instances."""
from __future__ import annotations

import hashlib
import re

_VALID_ID = re.compile(r"[A-Za-z0-9]+\Z")
_LEGACY_PATTERNS = (
    ("featured_products", re.compile(r"ss_featured_products_([0-9a-f]{8})\Z")),
    ("hero", re.compile(r"ss_hero_([0-9a-f]{10})\Z")),
    ("categories", re.compile(r"ss_categories_([0-9a-f]{10})\Z")),
    ("category_block", re.compile(r"ss_cat_([0-9a-f]{10})\Z")),
    # Historical homepage_collections._section_id: normalized slug (max 12 chars), SHA1[:8].
    ("collection", re.compile(r"ss_([a-z0-9_]{1,12})_([0-9a-f]{8})\Z")),
)


def is_valid_shopify_instance_id(value: object) -> bool:
    return isinstance(value, str) and bool(_VALID_ID.fullmatch(value))


def shopify_instance_id(namespace: str, key: object, *, prefix: str = "ss") -> str:
    """Build a deterministic, portable alphanumeric section/block instance ID."""
    clean = lambda value: re.sub(r"[^A-Za-z0-9]", "", str(value)).lower()
    normalized_namespace = clean(namespace)
    normalized_prefix = clean(prefix)
    if not normalized_namespace or not normalized_prefix:
        raise ValueError("prefix and namespace must contain at least one alphanumeric character")
    canonical = f"{normalized_namespace}:{str(key)}".encode("utf-8")
    result = normalized_prefix + normalized_namespace + hashlib.sha1(canonical).hexdigest()[:12]
    if not is_valid_shopify_instance_id(result):
        raise ValueError("generated Shopify instance ID is invalid")
    return result


def legacy_shopify_instance_kind(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    for kind, pattern in _LEGACY_PATTERNS:
        if pattern.fullmatch(value):
            return kind
    return None


def legacy_featured_id_for_store(store_id: object) -> str:
    """Exact ID generated by the historical featured-products implementation."""
    return "ss_featured_products_" + hashlib.sha1(str(store_id).encode("utf-8")).hexdigest()[:8]


def legacy_managed_id(namespace: str, key: object) -> str:
    """Historical homepage_automation._managed_id format (for exact migrations only)."""
    kind = re.sub(r"[^A-Za-z0-9]", "", str(namespace)).lower()
    return f"ss_{kind}_" + hashlib.sha1(str(key).encode("utf-8")).hexdigest()[:10]


def legacy_collection_section_id(key: object) -> str:
    """Historical homepage_collections._section_id format (for exact migrations only)."""
    slug = re.sub(r"[^a-z0-9]+", "_", str(key).casefold()).strip("_")[:12] or "collection"
    digest = hashlib.sha1(str(key).encode("utf-8")).hexdigest()[:8]
    return f"ss_{slug}_{digest}"
